### ISSUE TITLE
1.20.1 ecoehants error 

### ISSUE THREAD

**Issue by ClancyNGC1277** [Auxilor/libreforge#103]
[17:07:10] [Server thread/WARN]: [EcoEnchants] Task #3129 for EcoEnchants v10.26.1 generated an exception
java.lang.NullPointerException: Parameter specified as non-null is null: method com.willfp.ecoenchants.enchants.EcoEnchantLevel.<init>, parameter effects
	at com.willfp.ecoenchants.enchants.EcoEnchantLevel.<init>(EcoEnchantLevel.kt) ~[EcoEnchants-10.26.1-all.jar:?]
	at com.willfp.ecoenchants.enchants.LibReforgeEcoEnchant.createLevel(LibReforgeEcoEnchant.kt:26) ~[EcoEnchants-10.26.1-all.jar:?]
	at com.willfp.ecoenchants.enchants.EcoEnchant.getLevel$lambda-5(EcoEnchant.kt:208) ~[EcoEnchants-10.26.1-all.jar:?]
	at com.github.benmanes.caffeine.cache.UnboundedLocalCache.lambda$computeIfAbsent$2(UnboundedLocalCache.java:297) ~[eco-6.65.3-all.jar:?]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
	at com.github.benmanes.caffeine.cache.UnboundedLocalCache.computeIfAbsent(UnboundedLocalCache.java:293) ~[eco-6.65.3-all.jar:?]
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:110) ~[eco-6.65.3-all.jar:?]
	at com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62) ~[eco-6.65.3-all.jar:?]
	at com.willfp.ecoenchants.enchants.EcoEnchant.getLevel(EcoEnchant.kt:207) ~[EcoEnchants-10.26.1-all.jar:?]
	at com.willfp.ecoenchants.target.EnchantLookup.getActiveEnchantsInSlots(EnchantLookup.kt:184) ~[EcoEnchants-10.26.1-all.jar:?]
	at com.willfp.ecoenchants.target.EnchantLookup.getActiveEnchants(EnchantLookup.kt:202) ~[EcoEnchants-10.26.1-all.jar:?]
	at com.willfp.ecoenchants.target.EnchantLookup.getActiveEnchantLevel(EnchantLookup.kt:226) ~[EcoEnchants-10.26.1-all.jar:?]
	at com.willfp.ecoenchants.target.EnchantLookup.hasEnchantActive(EnchantLookup.kt:278) ~[EcoEnchants-10.26.1-all.jar:?]
	at com.willfp.ecoenchants.enchants.impl.EnchantmentRepairing.handleRepairing(EnchantmentRepairing.kt:30) ~[EcoEnchants-10.26.1-all.jar:?]
	at com.willfp.ecoenchants.enchants.impl.EnchantmentRepairing.onInit$lambda-0(EnchantmentRepairing.kt:22) ~[EcoEnchants-10.26.1-all.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.1.jar:git-Purpur-2016]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[purpur-1.20.1.jar:git-Purpur-2016]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1507) ~[purpur-1.20.1.jar:git-Purpur-2016]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.20.1.jar:git-Purpur-2016]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1421) ~[purpur-1.20.1.jar:git-Purpur-2016]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[purpur-1.20.1.jar:git-Purpur-2016]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2016]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[17:07:10] [Server thread/WARN]: [libreforge] Task #3139 for libreforge v4.25.1 generated an exception
java.lang.NullPointerException: Parameter specified as non-null is null: method com.willfp.ecoenchants.enchants.EcoEnchantLevel.<init>, parameter effects
	at com.willfp.ecoenchants.enchants.EcoEnchantLevel.<init>(EcoEnchantLevel.kt) ~[EcoEnchants-10.26.1-all.jar:?]
	at com.willfp.ecoenchants.enchants.LibReforgeEcoEnchant.createLevel(LibReforgeEcoEnchant.kt:26) ~[EcoEnchants-10.26.1-all.jar:?]
	at com.willfp.ecoenchants.enchants.EcoEnchant.getLevel$lambda-5(EcoEnchant.kt:208) ~[EcoEnchants-10.26.1-all.jar:?]
	at com.github.benmanes.caffeine.cache.UnboundedLocalCache.lambda$computeIfAbsent$2(UnboundedLocalCache.java:297) ~[eco-6.65.3-all.jar:?]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
	at com.github.benmanes.caffeine.cache.UnboundedLocalCache.computeIfAbsent(UnboundedLocalCache.java:293) ~[eco-6.65.3-all.jar:?]
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:110) ~[eco-6.65.3-all.jar:?]
	at com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62) ~[eco-6.65.3-all.jar:?]
	at com.willfp.ecoenchants.enchants.EcoEnchant.getLevel(EcoEnchant.kt:207) ~[EcoEnchants-10.26.1-all.jar:?]
	at com.willfp.ecoenchants.target.EnchantLookup.getHeldEnchantLevels(EnchantLookup.kt:305) ~[EcoEnchants-10.26.1-all.jar:?]
	at com.willfp.ecoenchants.EcoEnchantsPlugin$handleEnable$1.invoke(EcoEnchantsPlugin.kt:64) ~[EcoEnchants-10.26.1-all.jar:?]
	at com.willfp.ecoenchants.EcoEnchantsPlugin$handleEnable$1.invoke(EcoEnchantsPlugin.kt:64) ~[EcoEnchants-10.26.1-all.jar:?]
	at com.willfp.libreforge.HolderProviderKt$registerHolderProvider$1.provide(HolderProvider.kt:108) ~[libreforge-4.25.1-all.jar:?]
	at com.willfp.libreforge.HolderProviderKt._get_holders_$lambda-7(HolderProvider.kt:182) ~[libreforge-4.25.1-all.jar:?]
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$13(BoundedLocalCache.java:2550) ~[eco-6.65.3-all.jar:?]
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916) ~[?:?]
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2548) ~[eco-6.65.3-all.jar:?]
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2531) ~[eco-6.65.3-all.jar:?]
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:110) ~[eco-6.65.3-all.jar:?]
	at com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62) ~[eco-6.65.3-all.jar:?]
	at com.willfp.libreforge.HolderProviderKt.getHolders(HolderProvider.kt:181) ~[libreforge-4.25.1-all.jar:?]
	at com.willfp.libreforge.HolderProviderKt.calculateActiveEffects(HolderProvider.kt:275) ~[libreforge-4.25.1-all.jar:?]
	at com.willfp.libreforge.HolderProviderKt.updateEffects(HolderProvider.kt:294) ~[libreforge-4.25.1-all.jar:?]
	at com.willfp.libreforge.HolderProviderKt.refreshHolders(HolderProvider.kt:126) ~[libreforge-4.25.1-all.jar:?]
	at com.willfp.libreforge.LibreforgeSpigotPlugin.createTasks$lambda-0(LibreforgeSpigotPlugin.kt:114) ~[libreforge-4.25.1-all.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.1.jar:git-Purpur-2016]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[purpur-1.20.1.jar:git-Purpur-2016]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1507) ~[purpur-1.20.1.jar:git-Purpur-2016]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.20.1.jar:git-Purpur-2016]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1421) ~[purpur-1.20.1.jar:git-Purpur-2016]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[purpur-1.20.1.jar:git-Purpur-2016]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2016]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by CallumJohnson** [comment]
Unsupported version `1.20.1`.
