### ISSUE TITLE
EcoEnchants 1.17.1 libreforge error

### ISSUE THREAD

**Issue by DxRyus** [Auxilor/libreforge#116]
java.lang.NoClassDefFoundError: net/kyori/adventure/text/minimessage/MiniMessage
        at com.willfp.libreforge.integrations.paper.impl.EffectSendMinimessage.<clinit>(EffectSendMinimessage.kt:23) ~[libreforge-4.29.1.jar:?]
        at com.willfp.libreforge.integrations.paper.PaperIntegration.load(PaperIntegration.kt:31) ~[libreforge-4.29.1.jar:?]
        at com.willfp.libreforge.LibreforgeSpigotPlugin.handleEnable(LibreforgeSpigotPlugin.kt:73) ~[libreforge-4.29.1.jar:?]
        at com.willfp.eco.core.EcoPlugin.handleLifecycle(EcoPlugin.java:701) ~[eco-6.65.4-all.jar:?]
        at com.willfp.eco.core.EcoPlugin.onEnable(EcoPlugin.java:461) ~[eco-6.65.4-all.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-408]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-408]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-408]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Paper-408]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Paper-408]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:733) ~[patched_1.17.1.jar:git-Paper-408]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:317) ~[patched_1.17.1.jar:git-Paper-408]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[patched_1.17.1.jar:git-Paper-408]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-408]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.kyori.adventure.text.minimessage.MiniMessage
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[patched_1.17.1.jar:git-Paper-408]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.1.jar:git-Paper-408]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 15 more

![image](https://github.com/Auxilor/libreforge/assets/139377820/6a130fdd-69b1-4dbc-8f93-4ca9d4ecb501)

**Comment by CallumJohnson** [comment]
Unsupported version `1.17.1`
