### ISSUE TITLE
Cant's Work

### ISSUE THREAD

**Issue by 849025143** [Auxilor/libreforge#158]
[09:35:10] [Server thread/ERROR]: Error occurred while enabling libreforge v4.56.5 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class com.willfp.libreforge.effects.Effects
        at com.willfp.libreforge.integrations.vault.VaultIntegration.load(VaultIntegration.kt:16) ~[?:?]
        at com.willfp.libreforge.LibreforgeSpigotPlugin.loadIntegrationLoaders$lambda$10(LibreforgeSpigotPlugin.kt:180) ~[?:?]
        at com.willfp.eco.core.integrations.IntegrationLoader.load(IntegrationLoader.java:60) ~[?:?]
        at com.willfp.eco.core.EcoPlugin.lambda$onEnable$1(EcoPlugin.java:403) ~[?:?]
        at java.util.Arrays$ArrayList.forEach(Arrays.java:4305) ~[?:?]
        at com.willfp.eco.core.EcoPlugin.onEnable(EcoPlugin.java:400) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267) ~[banner-1.20.1-599-server.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) ~[banner-1.20.1-599-server.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:482) ~[banner-1.20.1-599-server.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:537) ~[banner-1.20.1-599-server.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:459) ~[banner-1.20.1-599-server.jar:?]
        at net.minecraft.server.MinecraftServer.handler$zjj000$banner$enablePlugins(MinecraftServer.java:2208) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:339) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3823(class_3176.java:169) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:2061) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.ExceptionInInitializerError [in thread "Server thread"]
        at com.willfp.libreforge.effects.Effects.<clinit>(Effects.kt:315) ~[?:?]
        at com.willfp.ecoenchants.enchant.impl.LibreforgeEcoEnchant.<init>(LibreforgeEcoEnchant.kt:38) ~[?:?]
        at com.willfp.ecoenchants.enchant.EcoEnchants.acceptPreloadConfig(EcoEnchants.kt:69) ~[?:?]
        at com.willfp.ecoenchants.libreforge.loader.LibreforgePlugin$loadCategory$3.invoke(LibreforgePlugin.kt:98) ~[?:?]
        at com.willfp.ecoenchants.libreforge.loader.LibreforgePlugin$loadCategory$3.invoke(LibreforgePlugin.kt:95) ~[?:?]
        at com.willfp.ecoenchants.libreforge.loader.LibreforgePlugin.withLogs(LibreforgePlugin.kt:131) ~[?:?]
        at com.willfp.ecoenchants.libreforge.loader.LibreforgePlugin.loadCategory(LibreforgePlugin.kt:95) ~[?:?]
        at com.willfp.ecoenchants.libreforge.loader.LibreforgePlugin._init_$lambda$2(LibreforgePlugin.kt:53) ~[?:?]
        at com.willfp.eco.core.EcoPlugin.handleLifecycle(EcoPlugin.java:731) ~[?:?]
        at com.willfp.eco.core.EcoPlugin.onLoad(EcoPlugin.java:531) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:439) ~[banner-1.20.1-599-server.jar:?]
        at net.minecraft.class_3176.handler$zkk001$banner$initServer(class_3176.java:686) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3823(class_3176.java:166) ~[server-intermediary.jar:?]
        ... 3 more

**Comment by CallumJohnson** [comment]
Outdated, thanks for your issue.
