### ISSUE TITLE
Creature problem

### ISSUE THREAD

**Issue by HyperFearless** [Auxilor/libreforge#49]
[17:54:00 ERROR]: Could not pass event PlayerInteractEvent to EcoEnchants v9.0.0-b10
java.lang.ClassCastException: class com.willfp.eco.internal.entities.EcoDummyEntity cannot be cast to class org.bukkit.entity.Mob (com.willfp.eco.internal.entities.EcoDummyEntity is in unnamed module of loader 'eco-6.38.3-all.jar' @2ad4e967; org.bukkit.entity.Mob is in unnamed module of loader java.net.URLClassLoader @61e717c2)
        at com.willfp.ecoenchants.libreforge.effects.effects.EffectSpawnMobs.handle(EffectSpawnMobs.kt:51) ~[?:?]
        at com.willfp.ecoenchants.libreforge.effects.ConfiguredEffect.invoke$eco_api(ConfiguredEffect.kt:214) ~[?:?]
        at com.willfp.ecoenchants.libreforge.chains.ChainComponentEffect.invoke(EffectChain.kt:34) ~[?:?]
        at com.willfp.ecoenchants.libreforge.chains.NormalChainInvoker.invoke(ChainInvokers.kt:22) ~[?:?]
        at com.willfp.ecoenchants.libreforge.chains.EffectChain.invoke(EffectChain.kt:16) ~[?:?]
        at com.willfp.ecoenchants.libreforge.effects.effects.EffectRunChainInline.handle(EffectRunChainInline.kt:38) ~[?:?]
        at com.willfp.ecoenchants.libreforge.effects.ConfiguredEffect.invoke$eco_api(ConfiguredEffect.kt:215) ~[?:?]
        at com.willfp.ecoenchants.libreforge.effects.ConfiguredEffect.invoke$eco_api$default(ConfiguredEffect.kt:48) ~[?:?]
        at com.willfp.ecoenchants.libreforge.triggers.Trigger.processTrigger(Trigger.kt:67) ~[?:?]
        at com.willfp.ecoenchants.libreforge.triggers.Trigger.processTrigger(Trigger.kt:30) ~[?:?]
        at com.willfp.ecoenchants.libreforge.triggers.Trigger.processTrigger$default(Trigger.kt:29) ~[?:?]
        at com.willfp.ecoenchants.libreforge.triggers.triggers.TriggerAltClick.handle(TriggerAltClick.kt:112) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor331.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-387]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:669) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:544) ~[paper-1.18.2.jar:git-Paper-387]
        at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:507) ~[paper-1.18.2.jar:git-Paper-387]
        at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:502) ~[paper-1.18.2.jar:git-Paper-387]
        at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:498) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItem(ServerGamePacketListenerImpl.java:1910) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:28) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.a(ServerboundUseItemPacket.java:8) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1400) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1377) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1370) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1348) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-387]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by WillFP** [comment]
Can you send me your config?
